# Generated by Django 5.1.5 on 2025-08-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoDeteccao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.CharField(choices=[('Correto', 'Correto'), ('Parcialmente Correto', 'Parcialmente Correto'), ('Incorreto', 'Incorreto')], help_text='Avaliação geral da detecção', max_length=20, verbose_name='Avaliação')),
                ('criticas', models.TextField(blank=True, help_text='Críticas construtivas sobre a detecção', null=True, verbose_name='Críticas')),
                ('sugestoes', models.TextField(blank=True, help_text='Sugestões de melhoria para o sistema', null=True, verbose_name='Sugestões')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Avaliação de Detecção',
                'verbose_name_plural': 'Avaliações de Detecção',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Deteccao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.CharField(choices=[('Normal', 'Normal'), ('Tuberculose', 'Tuberculose'), ('Pneumonia', 'Pneumonia')], max_length=20, verbose_name='Diagnóstico')),
                ('resultados_completos', models.JSONField(help_text='Probabilidades de todas as classes/doenças', verbose_name='Resultados Completos')),
                ('probabilidade', models.DecimalField(decimal_places=2, help_text='Probabilidade em porcentagem (0-100)', max_digits=5, verbose_name='Probabilidade')),
                ('descobertas', models.TextField(help_text='Descobertas detalhadas da análise', verbose_name='Descobertas')),
                ('interpretacao', models.TextField(help_text='Interpretação clínica dos resultados', verbose_name='Interpretação')),
                ('pontuacao_de_confianca', models.TextField(help_text='Pontuação de Confiança', verbose_name='Pontuação de Confiança')),
                ('estado', models.CharField(choices=[('Pendente', 'Pendente'), ('Em Análise', 'Em Análise'), ('Concluído', 'Concluído'), ('Revisão Necessária', 'Revisão Necessária')], default='Concluído', max_length=20, verbose_name='Estado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Detecção',
                'verbose_name_plural': 'Detecções',
                'ordering': ['-criado_em'],
            },
        ),
    ]
