# Generated by Django 5.1.5 on 2025-02-11 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('radiografias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deteccao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doenca', models.CharField(choices=[('Tuberculose', 'Tuberculose'), ('Pneumonia', 'Pneumonia'), ('Covid-19', 'Covid-19')], max_length=20, verbose_name='Doença')),
                ('resultado', models.CharField(help_text='Resultado da análise de detecção', max_length=255, verbose_name='Resultado')),
                ('probabilidade', models.DecimalField(decimal_places=2, help_text='Probabilidade em porcentagem (0-100)', max_digits=5, verbose_name='Probabilidade')),
                ('descobertas', models.TextField(help_text='Descobertas detalhadas da análise', verbose_name='Descobertas')),
                ('estado', models.CharField(choices=[('Pendente', 'Pendente'), ('Em Análise', 'Em Análise'), ('Concluído', 'Concluído'), ('Revisão Necessária', 'Revisão Necessária')], default='Pendente', max_length=20, verbose_name='Estado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('radiografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deteccoes', to='radiografias.radiografia', verbose_name='Radiografia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deteccoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Detecção',
                'verbose_name_plural': 'Detecções',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoDeteccao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.CharField(choices=[('Correto', 'Correto'), ('Parcialmente Correto', 'Parcialmente Correto'), ('Incorreto', 'Incorreto')], help_text='Avaliação geral da detecção', max_length=20, verbose_name='Avaliação')),
                ('criticas', models.TextField(blank=True, help_text='Críticas construtivas sobre a detecção', null=True, verbose_name='Críticas')),
                ('sugestoes', models.TextField(blank=True, help_text='Sugestões de melhoria para o sistema', null=True, verbose_name='Sugestões')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_deteccao', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('deteccao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='deteccoes.deteccao', verbose_name='Detecção')),
            ],
            options={
                'verbose_name': 'Avaliação de Detecção',
                'verbose_name_plural': 'Avaliações de Detecção',
                'ordering': ['-criado_em'],
                'unique_together': {('deteccao', 'usuario')},
            },
        ),
    ]
