# Generated by Django 5.1.5 on 2025-08-29 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deteccoes', '0001_initial'),
        ('modelos', '0001_initial'),
        ('radiografias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaodeteccao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_deteccao', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='deteccao',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deteccoes', to='modelos.modelo', verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='deteccao',
            name='radiografia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deteccoes', to='radiografias.radiografia', verbose_name='Radiografia'),
        ),
        migrations.AddField(
            model_name='deteccao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deteccoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='avaliacaodeteccao',
            name='deteccao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='deteccoes.deteccao', verbose_name='Detecção'),
        ),
        migrations.AlterUniqueTogether(
            name='avaliacaodeteccao',
            unique_together={('deteccao', 'usuario')},
        ),
    ]
