# Generated by Django 5.1.5 on 2026-01-14 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deteccoes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deteccao',
            name='descobertas',
        ),
        migrations.RemoveField(
            model_name='deteccao',
            name='interpretacao',
        ),
        migrations.RemoveField(
            model_name='deteccao',
            name='pontuacao_de_confianca',
        ),
    ]
