# Generated by Django 5.1.5 on 2025-01-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Gênero')),
                ('tipo_sanguineo', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True, verbose_name='Tipo Sanguíneo')),
                ('nome_da_mae', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da mãe')),
                ('numero_bi', models.CharField(blank=True, help_text='Número do BI', max_length=30, null=True, unique=True, verbose_name='Número do BI')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('contato_emergencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contacto de Emergência')),
                ('municipio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Município')),
                ('provincia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Província')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pacientes/fotos', verbose_name='Foto')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['nome', 'sobrenome'],
            },
        ),
    ]
