# Generated by Django 5.1.5 on 2025-02-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_paciente_numero_processo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='numero_processo',
            field=models.CharField(editable=False, help_text='Formato: pv[ano][número sequencial]', max_length=12, unique=True, verbose_name='Número de Processo'),
        ),
    ]
