# Generated by Django 5.1.5 on 2025-08-29 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome identificador do modelo de IA', max_length=100, verbose_name='Nome do Modelo')),
                ('versao', models.CharField(help_text='Versão do modelo (ex: 1.0, 2.1, etc.)', max_length=20, verbose_name='Versão')),
                ('data_treino', models.DateField(help_text='Data em que o modelo foi treinado', verbose_name='Data do Treino')),
                ('acuracia', models.DecimalField(decimal_places=2, help_text='Acurácia do modelo em porcentagem (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Acurácia')),
                ('precisao', models.DecimalField(decimal_places=2, help_text='Precisão do modelo em porcentagem (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Precisão')),
                ('recall', models.DecimalField(decimal_places=2, help_text='Recall do modelo em porcentagem (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Recall')),
                ('diretorio', models.CharField(help_text='Caminho para o diretório contendo modelo.keras e config.json, ou URL do modelo', max_length=500, verbose_name='Diretório/URL do Modelo')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do modelo e suas características', null=True, verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, help_text='Define se o modelo está ativo para uso no sistema', verbose_name='Modelo Ativo')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'ordering': ['-data_treino', '-criado_em'],
            },
        ),
    ]
