# Generated by Django 5.1.5 on 2025-08-29 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modelos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='usuario',
            field=models.ForeignKey(help_text='Usuário responsável pelo cadastro do modelo', on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável'),
        ),
        migrations.AlterUniqueTogether(
            name='modelo',
            unique_together={('nome', 'versao')},
        ),
    ]
