# Generated by Django 5.1.5 on 2025-08-29 15:00

import apps.radiografias.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Radiografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do Exame')),
                ('tipo', models.CharField(choices=[('Raio-X', 'Raio-X'), ('Tomografia Computadorizada', 'Tomografia Computadorizada')], max_length=40, verbose_name='Tipo de Exame')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('equipamento_usado', models.CharField(choices=[('Radiografia Digital (DR)', 'Radiografia Digital (DR)'), ('Radiografia Computadorizada (CR)', 'Radiografia Computadorizada (CR)'), ('Radiografia Convencional', 'Radiografia Convencional'), ('Equipamento Portátil', 'Equipamento Portátil')], max_length=50, verbose_name='Equipamento Utilizado')),
                ('notas_tecnicas', models.TextField(blank=True, null=True, verbose_name='Notas Técnicas')),
                ('qualidade_da_imagem', models.CharField(choices=[('Ótima', 'Ótima'), ('Boa', 'Boa'), ('Regular', 'Regular'), ('Ruim', 'Ruim')], max_length=10, verbose_name='Qualidade da Imagem')),
                ('imagem', models.ImageField(help_text='Formatos aceitos: .jpg, .jpeg, .png', upload_to=apps.radiografias.models.radiografia_imagem_path, verbose_name='Imagem')),
                ('dose_de_radiacao', models.DecimalField(blank=True, decimal_places=2, help_text='Dose de radiação em millisieverts (mSv)', max_digits=5, null=True, verbose_name='Dose de Radiação (mSv)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radiografias', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Radiografia',
                'verbose_name_plural': 'Radiografias',
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
